### ISSUE TITLE
Cache setting to false doesn't seem to work with browser-sync

### ISSUE THREAD

**Issue by devshack** [mallocator/gulp-international#1]
I'm using gulp-international to create a static website, together with gulp-merge-json, gulp-mustache, browser-sync, gulp-sass etc.

I also use run-sequence to make sure that various tasks are completed.

Here is what my gulpfile basicly does:
1. Run the task **gulp-merge-json** : it takes several splitted language files (one per page) and combines it to one file called de.json
2. Run the task **mustache** : It creates a .html file out of various .mustache templates
3. Run the task **international** : it takes the above created de.json and replaces all placeholders in the above created .html files

That's the task, using run-sequence:

```
gulp.task('build-pages', function (callback) {
    runSequence(
        'merge-json-locale',
        'mustache',
        'international',
        callback
    );
});
```

This task works perfecly and as expected when I run it via terminal (> gulp build-pages).

But when I try to include this task into the plugin **browser-sync**, the task **international** always seems to use an old version of the generated de.json.

I have already tried to turn the option "cache" to false, but it didn't change anything. No matter how much I change something in my language files - everything works (auto generation of the combined de.json, auto generation of the .html files) - your plugin doesn't use the fresh de.json.

Here is the main part of my gulpfile:

```
var gulp = require('gulp');
var gutil = require('gulp-util');
var plumber = require('gulp-plumber');
var sass = require('gulp-sass');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var cachebust = require('gulp-cache-bust');
var runSequence = require('run-sequence');
var browserSync = require('browser-sync');
var del = require('del');
var mergejson = require('gulp-merge-json');
var international = require('gulp-international');
var mustache = require('gulp-mustache');

const reload = browserSync.reload;

// create html pages out from mustache templates
gulp.task('mustache', function () {

    return gulp.src("dev/templates/*.mustache")
        .pipe(mustache({},{extension: '.html'}))
        .pipe(gulp.dest('.tmp'));

});

// combine json locale files
gulp.task('merge-json-locale', function() {

    // merge de
    del(['.tmp/locales/*.json'], {dryRun: false}).then(paths => {
        return gulp.src('dev/locales/partials/de/**/*.json')
            .pipe(mergejson('de.json'))
            .pipe(gulp.dest('.tmp/locales'));
    });

    // merge en
    //gulp.src('./dev/locales/partials/en/**/*.json')
    //  .pipe(mergejson('en_US.json'))
    //  .pipe(gulp.dest('./dev/locales'));

});

// replace placeholder with locale values
gulp.task('international', function () {

    return gulp.src('.tmp/*.html')
        .pipe(international({
            cache: false,
            //dryRun: true,
            verbose: true,
            whitelist: 'de',
            locales: '.tmp/locales',
            filename: '${path}/${lang}/${name}.${ext}',
            encodeEntities: false,
            delimiter: {
              prefix: 'TORR.',
              stopCondition: /[^\.\w_\-]/
            }
        }))
        .pipe(gulp.dest('.tmp'))
        .pipe(gulp.dest('dist'))
        .pipe( browserSync.stream() );

});

gulp.task('build-pages', function (callback) {
    runSequence(
        'merge-json-locale',
        'mustache',
        'international',
        callback
    );
});
```

As mentioned, all the above task runs perfectly when I run this task once. But not with this task:

```
gulp.task('serve', ['css', 'js', 'build-pages'], () => {
    browserSync({
        notify: true,
        port: 9000,
        server: {
          baseDir: ['.tmp', 'dev'],
          index: "/de/case-congstar.html",
          routes: {
            '/bower_components': 'bower_components'
          }
        }
    });

    // Watch changes in the locales
    gulp.watch( ['dev/locales/partials/**/*.json'], ['build-pages'] );

    // Watch changes in the templates
    gulp.watch( ['dev/templates/**/*', 'dev/partials/**/*'], ['build-pages'] );

    // Watch changes in the styles
    gulp.watch( sassFiles, ['css']);

    // Watch changes in the javascripts
    gulp.watch( jsFiles, ['js']);

});
```

Any ideas? :-(

**Comment by mallocator** [comment]
So I'm thinking there might be 2 possible causes off the top of my head: 
1. The plugin still does some caching somewhere. Looking at the code I can't see how though.
2. BrowserSync doesn't pick up the changes that should trigger the plugin. 
I'm thinking that it is looking for `*.json` files only in the beginning when you launch the watch tasks. Once it has fetched all the json files in the directories it doesn't add newly generated ones it doesn't already know about. I'm using livereload for these tasks, but I often run into similar issues.

One thing you could try is to explicitly specify the filename in the watch definition. I haven't looked at these plugins too closely so far though, so I'm not sure what the inner working are.

**Comment by devshack** [comment]
Thanks, I'm gonna try that out. If it doesn't work, I'm afraid I need to find another gulp plugin for my project :(

**Comment by mallocator** [comment]
Yeah there's a bunch of plugins that do similar things, sorry if this didn't help. Searching for `gulp i18n` on npmjs.com should yield good results, I assume though that you're going to have the same problems with them (if not then an update here would be great so I know for sure it's a problem with this plugin).
