### ISSUE TITLE
Using ${path} under Windows causes to halt / freeze gulp

### ISSUE THREAD

**Issue by devshack** [mallocator/gulp-international#2]
Hi,

we're using this kind of option for creating the filename:

`filename: './${lang}/${path}/${name}/index.${ext}',`

Which works great unter a Unix-based system (just like OS X). ;)

But under Windows, it just causes gulp to freeze / halt. It's running forever and doesn't exit or displays any kind of error message.

We found out that it's caused by your method of extracting the ${path} - when changing the line 333 of your index.js into this (quick and dirty), everything works as expected:

```
// params.path = file.path.substring(file.base.length, file.path.lastIndexOf('/'));
if ( process.platform == 'win32' || process.platform == 'win64' ) {
  params.path = file.path.substring(file.base.length, file.path.lastIndexOf('\\'));
} else {
  params.path = file.path.substring(file.base.length, file.path.lastIndexOf('/'));
}
```

Maybe you could fix this in a similar way? It would be great! :)

**Comment by mallocator** [comment]
I just pushed a new version that should have all the paths fixed for windows using `path.sep`. I don't have a windows machine to test this on, so I'd appreciate some feedback wether this works.

Thanks

**Comment by devshack** [comment]
Thanks! I'm trying it out right now and let you know if it works.

**Update**: Works flawlessly! 👍  I can't update it via npm, tough. ;)

**Comment by mallocator** [comment]
Hmm weird, I had already published it and can't republish version 1.0.13. 
Maybe npmjs.com is experiencing some issues right now. 
In any case, I'll publish an up to date version (but it might end up being 1.0.14).

**Update:** Seems like the webpage is not updated, but if you check the command line client it's the latest version that has this fix.

**Comment by devshack** [comment]
I don't refer to the website, I always use the command line. ;-)

Right now it looks weird - I installed 1.0.13 via github.

Using a npm outdated gives me the following output:

![capturfiles](https://cloud.githubusercontent.com/assets/1962175/17015099/89b27f30-4f28-11e6-8be5-02259ca8ea27.png)

**Comment by mallocator** [comment]
Okay I figured it out. I forgot to add a .npmrc to the directory to skip our local npm repo, my bad.
Latest version is up now.
